# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/bram_256x104/bram_256x104.xci
# IP: The module: 'bram_256x104' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/bram_256x104/bram_256x104_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_256x104'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/bram_256x104/bram_256x104.xci
# IP: The module: 'bram_256x104' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/bram_256x104/bram_256x104_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_256x104'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
