# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -msgmgr_mode ooc_run
create_project -in_memory -part xc7vx485tffg1761-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.cache/wt [current_project]
set_property parent.project_path /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part xilinx.com:vc707:part0:1.1 [current_project]
set_property ip_output_repo /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
set_property include_dirs {
  /home/alessandro/Documents/openpiton/piton/design/include
  /home/alessandro/Documents/openpiton/piton/design/chipset/include
} [current_fileset]
set_property verilog_define {NO_SCAN FPGA_SYN NO_USE_IBM_SRAMS PITON_FPGA_SYNTH PITON_PROTO PITON_FULL_SYSTEM FPGA_SYN_1THREAD PITON_FPGA_NO_DMBR VC707_BOARD} [current_fileset]
read_ip -quiet /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem.xci
set_property is_locked true [get_files /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem.xci]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

set cached_ip [config_ip_cache -export -no_bom -use_project_ipc -dir /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.runs/afifo_splitter_mem_synth_1 -new_name afifo_splitter_mem -ip [get_ips afifo_splitter_mem]]

if { $cached_ip eq {} } {

synth_design -top afifo_splitter_mem -part xc7vx485tffg1761-2 -mode out_of_context

#---------------------------------------------------------
# Generate Checkpoint/Stub/Simulation Files For IP Cache
#---------------------------------------------------------
catch {
 write_checkpoint -force -noxdef -rename_prefix afifo_splitter_mem_ afifo_splitter_mem.dcp

 set ipCachedFiles {}
 write_verilog -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ afifo_splitter_mem_stub.v
 lappend ipCachedFiles afifo_splitter_mem_stub.v

 write_vhdl -force -mode synth_stub -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ afifo_splitter_mem_stub.vhdl
 lappend ipCachedFiles afifo_splitter_mem_stub.vhdl

 write_verilog -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ afifo_splitter_mem_sim_netlist.v
 lappend ipCachedFiles afifo_splitter_mem_sim_netlist.v

 write_vhdl -force -mode funcsim -rename_top decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix -prefix decalper_eb_ot_sdeen_pot_pi_dehcac_xnilix_ afifo_splitter_mem_sim_netlist.vhdl
 lappend ipCachedFiles afifo_splitter_mem_sim_netlist.vhdl

 config_ip_cache -add -dcp afifo_splitter_mem.dcp -move_files $ipCachedFiles -use_project_ipc -ip [get_ips afifo_splitter_mem]
}

rename_ref -prefix_all afifo_splitter_mem_

write_checkpoint -force -noxdef afifo_splitter_mem.dcp

catch { report_utilization -file afifo_splitter_mem_utilization_synth.rpt -pb afifo_splitter_mem_utilization_synth.pb }

if { [catch {
  file copy -force /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.runs/afifo_splitter_mem_synth_1/afifo_splitter_mem.dcp /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  write_verilog -force -mode synth_stub /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode synth_stub /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  write_verilog -force -mode funcsim /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  write_vhdl -force -mode funcsim /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}


} else {


if { [catch {
  file copy -force /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.runs/afifo_splitter_mem_synth_1/afifo_splitter_mem.dcp /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem.dcp
} _RESULT ] } { 
  send_msg_id runtcl-3 error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
  error "ERROR: Unable to successfully create or copy the sub-design checkpoint file."
}

if { [catch {
  file rename -force /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.runs/afifo_splitter_mem_synth_1/afifo_splitter_mem_stub.v /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_stub.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a Verilog synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.runs/afifo_splitter_mem_synth_1/afifo_splitter_mem_stub.vhdl /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_stub.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create a VHDL synthesis stub for the sub-design. This may lead to errors in top level synthesis of the design. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.runs/afifo_splitter_mem_synth_1/afifo_splitter_mem_sim_netlist.v /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_sim_netlist.v
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the Verilog functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

if { [catch {
  file rename -force /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.runs/afifo_splitter_mem_synth_1/afifo_splitter_mem_sim_netlist.vhdl /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_sim_netlist.vhdl
} _RESULT ] } { 
  puts "CRITICAL WARNING: Unable to successfully create the VHDL functional simulation sub-design file. Post-Synthesis Functional Simulation with this file may not be possible or may give incorrect results. Error reported: $_RESULT"
}

}; # end if cached_ip 

if {[file isdir /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.ip_user_files/ip/afifo_splitter_mem]} {
  catch { 
    file copy -force /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_stub.v /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.ip_user_files/ip/afifo_splitter_mem
  }
}

if {[file isdir /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.ip_user_files/ip/afifo_splitter_mem]} {
  catch { 
    file copy -force /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_stub.vhdl /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.ip_user_files/ip/afifo_splitter_mem
  }
}
