# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem.xci
# IP: The module: 'afifo_splitter_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem/afifo_splitter_mem.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_splitter_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem/afifo_splitter_mem_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_splitter_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_splitter_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem.xci
# IP: The module: 'afifo_splitter_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem/afifo_splitter_mem.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_splitter_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem/afifo_splitter_mem_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_splitter_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/afifo_splitter_mem/afifo_splitter_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'afifo_splitter_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
