# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/clk_mmcm_memio_unit_tests/clk_mmcm_memio_unit_tests.xci
# IP: The module: 'clk_mmcm_memio_unit_tests' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/clk_mmcm_memio_unit_tests/clk_mmcm_memio_unit_tests_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_memio_unit_tests'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/clk_mmcm_memio_unit_tests/clk_mmcm_memio_unit_tests.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_memio_unit_tests'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/clk_mmcm_memio_unit_tests/clk_mmcm_memio_unit_tests_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_memio_unit_tests'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/clk_mmcm_memio_unit_tests/clk_mmcm_memio_unit_tests.xci
# IP: The module: 'clk_mmcm_memio_unit_tests' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/clk_mmcm_memio_unit_tests/clk_mmcm_memio_unit_tests_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_memio_unit_tests'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/clk_mmcm_memio_unit_tests/clk_mmcm_memio_unit_tests.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_memio_unit_tests'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/alessandro/Documents/embedded_prj/vc707/system/vc707_system/vc707_system.srcs/sources_1/ip/clk_mmcm_memio_unit_tests/clk_mmcm_memio_unit_tests_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_mmcm_memio_unit_tests'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
